name: Deploy HTML to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./index.html"
          target: "/var/www/app"

      - name: Configure Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo apt update -y
            sudo apt install -y nginx
            sudo tee /etc/nginx/sites-available/app > /dev/null <<EOF
            server {
                listen 80;
                server_name _;
                root /var/www/app;
                index index.html;
                location / { try_files \$uri \$uri/ =404; }
            }
            EOF
            sudo ln -sf /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app
            sudo nginx -t
            sudo systemctl restart nginx
